authentication_token:
    path: /api/login_check
    methods: ['POST']


#add un utilisateur
add_users:
    path: /api/admin/users
    methods: ['POST']
    controller: App\Controller\UserController::add

#add un utilisateur
add_grp_competence:
    path: /api/admin/grpecompetences
    methods: ['POST']
    controller: App\Controller\GroupeCompetenceController::create

#add un utilisateur
add_niveaux:
    path: /api/admin/competences
    methods: ['POST']
    controller: App\Controller\GroupeCompetenceController::addCompetenceAndLevels

#add un utilisateur
edit_niveaux:
    path: /api/admin/competences/{id}
    methods: ['PUT']
    controller: App\Controller\GroupeCompetenceController::editLevel