authentication_token:
    path: /api/login_check
    methods: ['POST']


#add un utilisateur
add_users:
    path: /api/admin/users
    methods: ['POST']
    controller: App\Controller\UserController::add

#edit un utilisateur
edit_users:
    path: /api/admin/users/{id}
    methods: ['POST']
    controller: App\Controller\UserController::editUser

#add un utilisateur
add_grp_competence:
    path: /api/admin/grpecompetences
    methods: ['POST']
    controller: App\Controller\GroupeCompetenceController::create

#add une comp
add_niveaux:
    path: /api/admin/competences
    methods: ['POST']
    controller: App\Controller\GroupeCompetenceController::addCompetenceAndLevels

#add un utilisateur
edit_niveaux:
    path: /api/admin/competences/{id}
    methods: ['PUT']
    controller: App\Controller\GroupeCompetenceController::editLevel

#creation groupe tags
create_grpe_tags:
   path: /api/admin/grptags
   controller: App\Controller\GroupeTagsController::createGroupeTags
   methods: ['POST']

#competencess d'un groupe de competences d'un referentiel
get_comp_gc_ref:
   path:  /api/admin/referentiels/{id}/grpecompetences/{idgc}
   controller: App\Controller\ReferentielController::getCompetences_gc_referentiels
   methods: ['GET']

#competencess d'un groupe de competences d'un referentiel
edit_groupe:
   path:  /api/admin/grpecompetences/{id}
   controller: App\Controller\GroupeCompetenceController::addOrRemoveCompetence
   methods: ['PUT']

#competencess d'un groupe de competences d'un referentiel
edit_grpe_tags:
   path:  /api/admin/grptags/{id}
   controller: App\Controller\GroupeTagsController::addOrRemoveTags
   methods: ['PUT']

#edit groupe de competences d'un referentiel
edit_referentiel:
   path:  /api/admin/referentiels/{id}
   controller: App\Controller\ReferentielController::editReferentiels
   methods: ['PUT']

#delete apprenant in groupe
retire_apprenant:
   path:  /api/admin/groupes/{id}/apprenants/{idA}
   controller: App\Controller\GroupesController::retireApprenantGroupe
   methods: ['DELETE']

#add groupe
add_groupe:
   path:  /api/admin/groupes
   controller: App\Controller\GroupesController::addGroupe
   methods: ['POST']

#add groupe
add_app_groupe:
   path:  /api/admin/groupes/{id}
   controller: App\Controller\GroupesController::addApprenanatGroupe
   methods: ['PUT']

#ajout promo
add_promo:
   path:  /api/admin/promo
   controller: App\Controller\PromosController::addPromos
   methods: ['POST']

app_groupe_promo:
   path:  /api/admin/promo/{idp}/groupes/{id}/apprenants
   controller: App\Controller\PromosController::getApprenantGroupePromo
   methods: ['GET']

#add or delete apprenants in promo
apprenant_promo:
   path:  /api/admin/promo/{id}/apprenants
   controller: App\Controller\PromosController::putApprenants
   methods: ['PUT']

#add or delete formateurs in promo
formateur_promo:
   path:  /api/admin/promo/{id}/formateurs
   controller: App\Controller\PromosController::putFormateurs
   methods: ['PUT']

   #add or delete formateurs in promo
edit_statut:
   path:  /api/admin/promo/{id}/groupes/{idg}
   controller: App\Controller\PromosController::editStatut
   methods: ['PUT']

   

   