authentication_token:
    path: /api/login_check
    methods: ['POST']


#add un utilisateur
add_users:
    path: /api/admin/users
    methods: ['POST']
    controller: App\Controller\UserController::add

#add un utilisateur
add_grp_competence:
    path: /api/admin/grpecompetences
    methods: ['POST']
    controller: App\Controller\GroupeCompetenceController::create